### PR TITLE
Fix sql-db tests. Bump Fabric8 Maven plugin to latest

### PR DESCRIPTION
**Pull request by juangon**
So it seems that, when deploying sql-db with empty configmap, app wasn't ready so it undeployed and wasn't ready. I added a default h2 datasource so it doesn't complain the first time and deploys succesfully, making possible to be changed by other configmaps later.

### CODE REVIEW

**Comment by Ladicek** [comment]
It's too easy to make the tests always use H2 and therefore become totally useless with this. I wonder why it used to work just fine...

**Comment by juangon** [comment]
My best guess is before 2.2.1 datsource was injected lazily instead of eager. But couldn't see any commit for something like that.

**Comment by Ladicek** [comment]
Ah yea, it might be caused by some WildFly changes.

**Comment by Ladicek** [comment]
The real problem, though, is that the way the `sql-db` test works is wrong -- the DB is deployed _after_ the app, it should be the opposite. I think we've done that because Arquillian Cube doesn't let us do it properly :-/ I'll take one more look if perhaps Arq Cube fires an event _before_ it gets to deploying the app, and if so, if that could be used to deploy the DB.

**Comment by juangon** [comment]
You mean for internal db right? We could use same approach as ssl-passthrough by using a script in env.setup.script.url?

**Comment by Ladicek** [comment]
We could do that, but I found a way that _might_ be even better :-)

**Comment by juangon** [comment]
Hehe great then

**Comment by Ladicek** [comment]
Closing in favor of #12.

**Pull request closed without merging**
