### PR TITLE
loading db image name from db.properties

### PR DESCRIPTION
**Pull request by penehyba**
running with -Dpostgresql.image=registry.access.redhat.com/rhscl/postgresql-95-rhel7 -Dmysql.image=registry.access.redhat.com/rhscl/mysql-57-rhel7 will override inner images

### CODE REVIEW

**Comment by Ladicek** [comment]
What's the actual usecase here?

**Comment by Ladicek** [comment]
I mean -- what do you want to achieve? I'm not totally against the solution here, but there might be a better way to do what you need to do.

**Comment by penehyba** [comment]
This is in reaction to https://issues.redhat.com/browse/CLOUD-3588?focusedCommentId=14107537&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14107537

I didn't want to include XTF solution as used in mentioned SB...another way can be to include this in pom..
@tomason  have a look at this please

**Comment by Ladicek** [comment]
How about we instead move to https://catalog.redhat.com/software/containers/detail/5aa63541ac3db95f196086f1 ? :-)

EDIT: We're on quite old DB versions here, so this would kill two birds with one stone :-)

**Comment by tomason** [comment]
@Ladicek Can we move to a newer version just like that?

@penehyba This solution is harder to override, can you, please, add a possibility to specify the image through system properties?

**Comment by tomason** [comment]
@Ladicek Can we move to a newer version just like that?

@penehyba I'm fine with either solution, as I said. Since this is already done, let's go with it (and update the default version in the properties file).

**Comment by Ladicek** [comment]
I have also just looked at the TS and it seems we don't use any other images, just MySQL and PostgreSQL (and of course OpenJDK, but that's specified in the POM and can be overridden easily).

Since it's quite unlikely we'll add more tests that use other images, I propose we just update the MySQL and PostgreSQL images to:

- `registry.access.redhat.com/rhscl/mysql-80-rhel7`
- `registry.access.redhat.com/rhscl/postgresql-10-rhel7`

Both of these images have an x86_64, s390x and ppc64le variants.

At the same time, we should also update to the latest JDBC drivers.

**Comment by Ladicek** [comment]
> @Ladicek Can we move to a newer version just like that?

I don't see why not.

**Comment by tomason** [comment]
> > @Ladicek Can we move to a newer version just like that?
> 
> I don't see why not.

How about this: https://access.redhat.com/articles/3986021?

**Comment by Ladicek** [comment]
If there's an s390x variant of PostgreSQL 9.x that the team will use, then sure. If they will use the override feature to use PostgreSQL 10, for which an s390x image is present, then there's no difference to what I'm proposing :-)

**Comment by penehyba** [comment]
changes in 2nd commit: 
2.5.1.Final-SNAPSHOT -> 2.6.1.Final-SNAPSHOT
https://mvnrepository.com/artifact/org.postgresql/postgresql  4.2.12
https://mvnrepository.com/artifact/mysql/mysql-connector-java 8.0.20
dballocator mysql80
dballocator postgresql115
+allowPublicKeyRetrieval=true for mysql

**Comment by Ladicek** [comment]
When I proposed updating to more up to date version of the DBs, I meant _without_ the properties file, which adds complexity to already quite complex tests...

**Review by Ladicek — APPROVED** [review]
OK, I don't understand why we need the ability to override the image with a system property, but this is reasonably straightforward, so fine.

**Pull request merged**
