### PR TITLE
Disable fabric8 maven plugin to cleanup resources to avoid race condi…+++

### PR DESCRIPTION
**Pull request by juangon**
…tions with our own resources manual deletion

### CODE REVIEW

**Comment by Ladicek** [comment]
Hmm. This will leave the test application deployed after the test, no?

**Comment by juangon** [comment]
Hmmm probably @Ladicek . Let me check tomorrow with namespace.destroy.enabled=true too

**Comment by juangon** [comment]
Well, probably namespace.destroy.enabled is too much. Let me think something else

**Comment by juangon** [comment]
An easy fix would be changing from BeforeClass to AfterClass the arquillian observer

**Comment by Ladicek** [comment]
It should probably be both before- and after-class.

**Comment by juangon** [comment]
Ok, will do those changes tomorrow. Thanks!

**Comment by juangon** [comment]
@Ladicek pushed those changes and tested

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
